### ISSUE TITLE
where is the dict.txt and other sample dataset

### ISSUE THREAD

**Issue by SeekPoint** [xylander23/New-Word-Detection#1]

**Comment by Mechanic934** [comment]
Hello, dict.txt is defined by yourself,  the format you can refer from  https://raw.githubusercontent.com/fxsjy/jieba/master/extra_dict/dict.txt.big

**Comment by SeekPoint** [comment]
and what about guangkai.txt

**Comment by Mechanic934** [comment]
It just a normal txt file, you can download any txt file like Journey to the West as a input file.

**Comment by SeekPoint** [comment]
maybe you can provide some necessary file for demo, thanks
